### Combine Estimation Results

This notebook reads CSV files with date stamps (e.g., `-12726`) from the results folder and combines them into a single DataFrame.

In [15]:
import pandas as pd
import glob
import re
from pathlib import Path

In [16]:
# Get all CSV files in the results folder
results_folder = Path('../results')
all_csv_files = list(results_folder.glob('*.csv'))

# Filter to only include files with a date pattern (e.g., -12726)
# Pattern: filename containing a hyphen followed by digits before .csv
date_pattern = re.compile(r'-\d+(-[\w-]+)?\.csv$')
dated_files = [f for f in all_csv_files if date_pattern.search(f.name)]

# Exclude melitz sigma-theta files and model2 files
dated_files = [f for f in dated_files if 'sigma-theta' not in f.name]
dated_files = [f for f in dated_files if 'model2' not in f.name]

# Only include files with the date 12726
dated_files = [f for f in dated_files if '12726' in f.name]

print(f"Found {len(dated_files)} files with date stamps:")
for f in dated_files:
    print(f"  - {f.name}")

Found 8 files with date stamps:
  - bejk-estimate-exact-12726.csv
  - bejk-estimate-over-12726.csv
  - ek-estimate-exact-12726.csv
  - ek-estimate-over-12726.csv
  - krugman-estimate-exact-12726.csv
  - krugman-estimate-over-12726.csv
  - melitz-estimate-exact-12726.csv
  - melitz-estimate-over-12726.csv

In [17]:
# Separate files into exact and over categories
exact_files = [f for f in dated_files if 'exact' in f.name]
over_files = [f for f in dated_files if 'over' in f.name]

print(f"Exact files ({len(exact_files)}):")
for f in exact_files:
    print(f"  - {f.name}")

print(f"\nOver files ({len(over_files)}):")
for f in over_files:
    print(f"  - {f.name}")

Exact files (4):
  - bejk-estimate-exact-12726.csv
  - ek-estimate-exact-12726.csv
  - krugman-estimate-exact-12726.csv
  - melitz-estimate-exact-12726.csv

Over files (4):
  - bejk-estimate-over-12726.csv
  - ek-estimate-over-12726.csv
  - krugman-estimate-over-12726.csv
  - melitz-estimate-over-12726.csv

In [18]:
# Read and combine EXACT files
exact_dfs = []
for file in exact_files:
    df = pd.read_csv(file)
    df['source_file'] = file.name
    exact_dfs.append(df)

exact_df = pd.concat(exact_dfs, ignore_index=True)

# Read and combine OVER files
over_dfs = []
for file in over_files:
    df = pd.read_csv(file)
    df['source_file'] = file.name
    over_dfs.append(df)

over_df = pd.concat(over_dfs, ignore_index=True)

# Set display options to show 2 decimal places
pd.set_option('display.float_format', '{:.2f}'.format)

print(f"Exact DataFrame: {len(exact_df)} rows")
print(f"Over DataFrame: {len(over_df)} rows")

Exact DataFrame: 12 rows
Over DataFrame: 12 rows

In [19]:
# Display EXACT results
print("=== EXACT Estimation Results ===")
exact_df.sort_values(by = ["θ"], inplace=True)

exact_df

=== EXACT Estimation Results ===

,θ,J,p10,p90,Jpercentile,model_moment,data_moment,model,method,year,source_file
1,2.73,0.00,2.66,2.85,0.49,0.98,0.98,bejk,exact,2011,bejk-estimate-exact-12726.csv
0,2.82,0.00,2.73,2.93,0.14,0.93,0.93,bejk,exact,2004,bejk-estimate-exact-12726.csv
2,2.87,0.00,2.76,3.00,0.69,0.91,0.91,bejk,exact,2017,bejk-estimate-exact-12726.csv
10,3.30,0.00,3.10,3.83,0.02,0.98,0.98,melitz,exact,2011,melitz-estimate-exact-12726.csv
11,3.32,0.00,2.83,3.73,0.15,0.91,0.91,melitz,exact,2017,melitz-estimate-exact-12726.csv
9,3.50,0.00,3.06,3.90,0.19,0.93,0.93,melitz,exact,2004,melitz-estimate-exact-12726.csv
4,3.94,0.00,3.81,4.08,0.80,0.98,0.98,ek,exact,2011,ek-estimate-exact-12726.csv
3,4.09,0.00,3.92,4.23,0.98,0.93,0.93,ek,exact,2004,ek-estimate-exact-12726.csv
5,4.19,0.00,4.05,4.34,0.34,0.91,0.91,ek,exact,2017,ek-estimate-exact-12726.csv
7,4.90,0.00,4.73,5.12,0.66,0.98,0.98,krugman,exact,2011,krugman-estimate-exact-12726.csv
8,5.17,0.00,4.94,5.41,0.46,0.91,0.91,krugman,exact,2017,krugman-estimate-exact-12726.csv
6,5.19,0.00,4.96,5.57,0.48,0.93,0.93,krugman,exact,2004,krugman-estimate-exact-12726.csv

In [20]:
# Save the combined results to CSV
exact_df.to_csv('combined-exact-results.csv', index=False, float_format='%.2f')
over_df.to_csv('combined-over-results.csv', index=False, float_format='%.2f')
print("Saved: combined-exact-results.csv")
print("Saved: combined-over-results.csv")

Saved: combined-exact-results.csv
Saved: combined-over-results.csv

In [21]:
# Display OVER results
print("=== OVER Estimation Results ===")
over_df

=== OVER Estimation Results ===

,θ,J,p10,p90,Jpercentile,model_moment_1,data_moment_1,model_moment_2,data_moment_2,model_moment_3,data_moment_3,model,method,year,source_file
0,2.76,23.31,2.71,2.83,0.68,0.95,0.93,0.36,0.37,0.07,0.09,bejk,over,2004,bejk-estimate-over-12726.csv
1,2.80,173.18,2.74,2.88,1.00,0.96,0.98,0.34,0.34,0.07,0.25,bejk,over,2011,bejk-estimate-over-12726.csv
2,2.88,180.72,2.81,2.95,1.00,0.91,0.91,0.33,0.32,0.06,0.20,bejk,over,2017,bejk-estimate-over-12726.csv
3,4.00,10.74,3.91,4.12,0.38,0.95,0.93,0.36,0.37,0.09,0.09,ek,over,2004,ek-estimate-over-12726.csv
4,4.07,136.76,3.99,4.18,0.99,0.95,0.98,0.34,0.34,0.09,0.25,ek,over,2011,ek-estimate-over-12726.csv
5,4.18,139.25,4.09,4.31,1.00,0.91,0.91,0.32,0.32,0.07,0.20,ek,over,2017,ek-estimate-over-12726.csv
6,3.76,1390.47,3.56,3.92,1.00,1.28,0.93,0.25,0.37,0.23,0.09,krugman,over,2004,krugman-estimate-over-12726.csv
7,3.49,983.90,3.34,3.60,1.00,1.38,0.98,0.25,0.34,0.23,0.25,krugman,over,2011,krugman-estimate-over-12726.csv
8,3.82,1411.74,3.64,3.98,1.00,1.23,0.91,0.21,0.32,0.20,0.20,krugman,over,2017,krugman-estimate-over-12726.csv
9,3.59,133.16,3.38,3.91,0.86,0.90,0.93,0.34,0.37,0.21,0.09,melitz,over,2004,melitz-estimate-over-12726.csv
10,3.15,60.78,2.91,3.67,0.53,1.03,0.98,0.29,0.34,0.25,0.25,melitz,over,2011,melitz-estimate-over-12726.csv
11,3.08,287.52,2.60,3.82,0.92,0.98,0.91,0.23,0.32,0.25,0.20,melitz,over,2017,melitz-estimate-over-12726.csv

In [24]:
# Combine BEJK sigma files
# Pattern: bejk-estimate-{exact|over}-{date}-sigma{value}.csv
sigma_pattern = re.compile(r'sigma(\d+)\.csv$')

bejk_sigma_files = [f for f in results_folder.glob('bejk-estimate-*-sigma*.csv')]

bejk_sigma_dfs = []
for file in bejk_sigma_files:
    df = pd.read_csv(file)
    df['source_file'] = file.name
    # Extract sigma value from filename (e.g. sigma15 -> 1.5)
    m = sigma_pattern.search(file.name)
    df['sigma'] = int(m.group(1)) / 10 if m else None
    # Extract identification type (exact or over)
    df['identification'] = 'exact' if 'exact' in file.name else 'over'
    bejk_sigma_dfs.append(df)

bejk_sigma_df = pd.concat(bejk_sigma_dfs, ignore_index=True)

# Split into exact and over
bejk_sigma_exact_df = bejk_sigma_df[bejk_sigma_df['identification'] == 'exact'].sort_values(by='sigma').reset_index(drop=True)
bejk_sigma_over_df  = bejk_sigma_df[bejk_sigma_df['identification'] == 'over'].sort_values(by='sigma').reset_index(drop=True)

bejk_sigma_exact_df.to_csv('combined-bejk-sigma-exact-results.csv', index=False, float_format='%.2f')
bejk_sigma_over_df.to_csv('combined-bejk-sigma-over-results.csv', index=False, float_format='%.2f')
print(f"Saved combined-bejk-sigma-exact-results.csv ({len(bejk_sigma_exact_df)} rows)")
print(f"Saved combined-bejk-sigma-over-results.csv ({len(bejk_sigma_over_df)} rows)")

print("\n=== BEJK Sigma — Exact ===")
display(bejk_sigma_exact_df)
print("\n=== BEJK Sigma — Over ===")
display(bejk_sigma_over_df)

Saved combined-bejk-sigma-exact-results.csv (15 rows)
Saved combined-bejk-sigma-over-results.csv (15 rows)

=== BEJK Sigma — Exact ===

,θ,J,p10,p90,Jpercentile,model_moment,data_moment,model,method,year,source_file,sigma,identification,model_moment_1,data_moment_1,model_moment_2,data_moment_2,model_moment_3,data_moment_3
0,2.82,0.00,2.73,2.93,0.25,0.93,0.93,bejk,exact,2004,bejk-estimate-exact-21126-sigma15.csv,1.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
1,2.73,0.00,2.66,2.85,0.70,0.98,0.98,bejk,exact,2011,bejk-estimate-exact-21126-sigma15.csv,1.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
2,2.87,0.00,2.76,3.00,0.82,0.91,0.91,bejk,exact,2017,bejk-estimate-exact-21126-sigma15.csv,1.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
3,3.07,0.00,2.95,3.17,0.39,0.93,0.93,bejk,exact,2004,bejk-estimate-exact-21126-sigma20.csv,2.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
4,2.99,0.00,2.89,3.09,0.52,0.98,0.98,bejk,exact,2011,bejk-estimate-exact-21126-sigma20.csv,2.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
5,3.12,0.00,3.00,3.22,0.85,0.91,0.91,bejk,exact,2017,bejk-estimate-exact-21126-sigma20.csv,2.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
6,3.28,0.00,3.13,3.36,0.63,0.93,0.93,bejk,exact,2004,bejk-estimate-exact-21126-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
7,3.19,0.00,3.08,3.30,0.89,0.98,0.98,bejk,exact,2011,bejk-estimate-exact-21126-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
8,3.33,0.00,3.21,3.43,0.31,0.91,0.91,bejk,exact,2017,bejk-estimate-exact-21126-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
9,3.28,0.00,3.13,3.36,0.63,0.93,0.93,bejk,exact,2004,bejk-estimate-exact-2626-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
10,3.19,0.00,3.08,3.30,0.89,0.98,0.98,bejk,exact,2011,bejk-estimate-exact-2626-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
11,3.33,0.00,3.21,3.43,0.31,0.91,0.91,bejk,exact,2017,bejk-estimate-exact-2626-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
12,3.43,0.00,3.28,3.53,0.23,0.93,0.93,bejk,exact,2004,bejk-estimate-exact-21126-sigma30.csv,3.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
13,3.33,0.00,3.22,3.45,0.40,0.98,0.98,bejk,exact,2011,bejk-estimate-exact-21126-sigma30.csv,3.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
14,3.49,0.00,3.36,3.61,0.06,0.91,0.91,bejk,exact,2017,bejk-estimate-exact-21126-sigma30.csv,3.00,exact,NaN,NaN,NaN,NaN,NaN,NaN

=== BEJK Sigma — Over ===

,θ,J,p10,p90,Jpercentile,model_moment,data_moment,model,method,year,source_file,sigma,identification,model_moment_1,data_moment_1,model_moment_2,data_moment_2,model_moment_3,data_moment_3
0,2.76,23.31,2.71,2.83,0.68,NaN,NaN,bejk,over,2004,bejk-estimate-over-21126-sigma15.csv,1.50,over,0.95,0.93,0.36,0.37,0.07,0.09
1,2.80,173.18,2.74,2.88,1.00,NaN,NaN,bejk,over,2011,bejk-estimate-over-21126-sigma15.csv,1.50,over,0.96,0.98,0.34,0.34,0.07,0.25
2,2.88,180.72,2.81,2.95,1.00,NaN,NaN,bejk,over,2017,bejk-estimate-over-21126-sigma15.csv,1.50,over,0.91,0.91,0.33,0.32,0.06,0.20
3,2.96,61.60,2.91,3.03,0.97,NaN,NaN,bejk,over,2004,bejk-estimate-over-21126-sigma20.csv,2.00,over,0.97,0.93,0.36,0.37,0.09,0.09
4,2.97,180.05,2.92,3.05,1.00,NaN,NaN,bejk,over,2011,bejk-estimate-over-21126-sigma20.csv,2.00,over,0.99,0.98,0.34,0.34,0.08,0.25
5,3.07,174.31,3.00,3.14,1.00,NaN,NaN,bejk,over,2017,bejk-estimate-over-21126-sigma20.csv,2.00,over,0.93,0.91,0.32,0.32,0.07,0.20
6,3.13,86.32,3.08,3.20,1.00,NaN,NaN,bejk,over,2004,bejk-estimate-over-21126-sigma25.csv,2.50,over,0.98,0.93,0.35,0.37,0.09,0.09
7,3.13,192.50,3.07,3.21,1.00,NaN,NaN,bejk,over,2011,bejk-estimate-over-21126-sigma25.csv,2.50,over,1.00,0.98,0.34,0.34,0.09,0.25
8,3.24,183.88,3.18,3.32,1.00,NaN,NaN,bejk,over,2017,bejk-estimate-over-21126-sigma25.csv,2.50,over,0.94,0.91,0.32,0.32,0.07,0.20
9,3.13,86.32,3.08,3.20,1.00,NaN,NaN,bejk,over,2004,bejk-estimate-over-2626-sigma25.csv,2.50,over,0.98,0.93,0.35,0.37,0.09,0.09
10,3.13,192.50,3.07,3.21,1.00,NaN,NaN,bejk,over,2011,bejk-estimate-over-2626-sigma25.csv,2.50,over,1.00,0.98,0.34,0.34,0.09,0.25
11,3.24,183.88,3.18,3.32,1.00,NaN,NaN,bejk,over,2017,bejk-estimate-over-2626-sigma25.csv,2.50,over,0.94,0.91,0.32,0.32,0.07,0.20
12,3.26,93.28,3.21,3.34,0.99,NaN,NaN,bejk,over,2004,bejk-estimate-over-21126-sigma30.csv,3.00,over,0.98,0.93,0.35,0.37,0.09,0.09
13,3.25,195.11,3.19,3.34,0.99,NaN,NaN,bejk,over,2011,bejk-estimate-over-21126-sigma30.csv,3.00,over,1.01,0.98,0.34,0.34,0.09,0.25
14,3.37,189.48,3.31,3.45,1.00,NaN,NaN,bejk,over,2017,bejk-estimate-over-21126-sigma30.csv,3.00,over,0.95,0.91,0.32,0.32,0.08,0.20

In [25]:
# Combine Krugman model2 files
krugman2_exact_df = pd.read_csv(results_folder / 'krugman-model2-estimate-exact-12726.csv')
krugman2_over_df  = pd.read_csv(results_folder / 'krugman-model2-estimate-over-12726.csv')

krugman2_exact_df.to_csv('combined-krugman-model2-exact-results.csv', index=False, float_format='%.2f')
krugman2_over_df.to_csv('combined-krugman-model2-over-results.csv', index=False, float_format='%.2f')
print(f"Saved combined-krugman-model2-exact-results.csv ({len(krugman2_exact_df)} rows)")
print(f"Saved combined-krugman-model2-over-results.csv ({len(krugman2_over_df)} rows)")

print("\n=== Krugman Model2 — Exact ===")
display(krugman2_exact_df)
print("\n=== Krugman Model2 — Over ===")
display(krugman2_over_df)

Saved combined-krugman-model2-exact-results.csv (1 rows)
Saved combined-krugman-model2-over-results.csv (3 rows)

=== Krugman Model2 — Exact ===

,θ,J,p10,p90,Jpercentile,model_moment,data_moment,model,method,year
0,3.65,0.00,3.76,3.81,0.00,0.91,0.91,krugman-model2,exact,2017

=== Krugman Model2 — Over ===

,θ,J,p10,p90,Jpercentile,model_moment_1,data_moment_1,model_moment_2,data_moment_2,model_moment_3,data_moment_3,model,method,year
0,3.72,122.12,3.55,3.93,0.89,0.92,0.93,0.34,0.37,0.21,0.09,krugman-model2,over,2004
1,3.39,45.51,3.03,3.57,0.42,1.05,0.98,0.31,0.34,0.25,0.25,krugman-model2,over,2011
2,3.51,45.42,3.23,4.02,0.36,0.95,0.91,0.28,0.32,0.22,0.20,krugman-model2,over,2017

In [26]:
# Combine Melitz model2 sigma files
# Pattern: melitz-model2-estimate-{exact|over}-{date}-sigma{value}.csv

melitz2_sigma_files = [f for f in results_folder.glob('melitz-model2-estimate-*-sigma*.csv')]

melitz2_sigma_dfs = []
for file in melitz2_sigma_files:
    df = pd.read_csv(file)
    df['source_file'] = file.name
    # Extract sigma value from filename (e.g. sigma15 -> 1.5)
    m = sigma_pattern.search(file.name)
    df['sigma'] = int(m.group(1)) / 10 if m else None
    # Extract identification type (exact or over)
    df['identification'] = 'exact' if 'exact' in file.name else 'over'
    melitz2_sigma_dfs.append(df)

melitz2_sigma_df = pd.concat(melitz2_sigma_dfs, ignore_index=True)

# Split into exact and over
melitz2_sigma_exact_df = melitz2_sigma_df[melitz2_sigma_df['identification'] == 'exact'].sort_values(by='sigma').reset_index(drop=True)
melitz2_sigma_over_df  = melitz2_sigma_df[melitz2_sigma_df['identification'] == 'over'].sort_values(by='sigma').reset_index(drop=True)

melitz2_sigma_exact_df.to_csv('combined-melitz-model2-sigma-exact-results.csv', index=False, float_format='%.2f')
melitz2_sigma_over_df.to_csv('combined-melitz-model2-sigma-over-results.csv', index=False, float_format='%.2f')
print(f"Saved combined-melitz-model2-sigma-exact-results.csv ({len(melitz2_sigma_exact_df)} rows)")
print(f"Saved combined-melitz-model2-sigma-over-results.csv ({len(melitz2_sigma_over_df)} rows)")

print("\n=== Melitz Model2 Sigma — Exact ===")
display(melitz2_sigma_exact_df)
print("\n=== Melitz Model2 Sigma — Over ===")
display(melitz2_sigma_over_df)

Saved combined-melitz-model2-sigma-exact-results.csv (12 rows)
Saved combined-melitz-model2-sigma-over-results.csv (9 rows)

=== Melitz Model2 Sigma — Exact ===

,θ,J,p10,p90,Jpercentile,model_moment,data_moment,model,method,year,source_file,sigma,identification,model_moment_1,data_moment_1,model_moment_2,data_moment_2,model_moment_3,data_moment_3
0,1.65,0.00,1.51,1.80,0.58,0.93,0.93,melitz-model2,exact,2004,melitz-model2-estimate-exact-21126-sigma15.csv,1.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
1,1.50,0.03,1.38,1.58,1.00,0.98,0.98,melitz-model2,exact,2011,melitz-model2-estimate-exact-21126-sigma15.csv,1.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
2,1.50,16.41,1.35,1.78,0.98,0.77,0.91,melitz-model2,exact,2017,melitz-model2-estimate-exact-21126-sigma15.csv,1.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
3,2.12,0.00,1.98,2.33,0.26,0.93,0.93,melitz-model2,exact,2004,melitz-model2-estimate-exact-21126-sigma20.csv,2.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
4,2.05,0.00,1.90,2.18,0.24,0.98,0.98,melitz-model2,exact,2011,melitz-model2-estimate-exact-21126-sigma20.csv,2.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
5,2.02,0.00,1.88,2.16,0.23,0.91,0.91,melitz-model2,exact,2017,melitz-model2-estimate-exact-21126-sigma20.csv,2.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
6,2.47,0.00,2.32,2.73,0.51,0.93,0.93,melitz-model2,exact,2004,melitz-model2-estimate-exact-21126-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
7,2.46,0.00,2.32,2.61,0.37,0.98,0.98,melitz-model2,exact,2011,melitz-model2-estimate-exact-21126-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
8,2.45,0.00,2.28,2.61,0.82,0.91,0.91,melitz-model2,exact,2017,melitz-model2-estimate-exact-21126-sigma25.csv,2.50,exact,NaN,NaN,NaN,NaN,NaN,NaN
9,2.77,0.00,2.53,3.02,0.21,0.93,0.93,melitz-model2,exact,2004,melitz-model2-estimate-exact-21126-sigma30.csv,3.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
10,2.79,0.00,2.57,2.98,0.49,0.98,0.98,melitz-model2,exact,2011,melitz-model2-estimate-exact-21126-sigma30.csv,3.00,exact,NaN,NaN,NaN,NaN,NaN,NaN
11,2.82,0.00,2.60,3.01,0.17,0.91,0.91,melitz-model2,exact,2017,melitz-model2-estimate-exact-21126-sigma30.csv,3.00,exact,NaN,NaN,NaN,NaN,NaN,NaN

=== Melitz Model2 Sigma — Over ===

,θ,J,p10,p90,Jpercentile,model_moment,data_moment,model,method,year,source_file,sigma,identification,model_moment_1,data_moment_1,model_moment_2,data_moment_2,model_moment_3,data_moment_3
0,2.05,149.52,1.93,2.51,0.49,NaN,NaN,melitz-model2,over,2004,melitz-model2-estimate-over-21126-sigma20.csv,2.00,over,0.97,0.93,0.38,0.37,0.30,0.09
1,2.03,12.31,1.96,2.50,0.10,NaN,NaN,melitz-model2,over,2011,melitz-model2-estimate-over-21126-sigma20.csv,2.00,over,0.99,0.98,0.33,0.34,0.31,0.25
2,1.99,47.97,1.92,9.20,0.15,NaN,NaN,melitz-model2,over,2017,melitz-model2-estimate-over-21126-sigma20.csv,2.00,over,0.94,0.91,0.30,0.32,0.31,0.20
3,2.55,156.06,2.40,2.98,0.71,NaN,NaN,melitz-model2,over,2004,melitz-model2-estimate-over-21126-sigma25.csv,2.50,over,0.88,0.93,0.38,0.37,0.25,0.09
4,2.50,40.17,2.33,2.76,0.33,NaN,NaN,melitz-model2,over,2011,melitz-model2-estimate-over-21126-sigma25.csv,2.50,over,0.95,0.98,0.38,0.34,0.26,0.25
5,2.52,26.78,2.34,2.85,0.29,NaN,NaN,melitz-model2,over,2017,melitz-model2-estimate-over-21126-sigma25.csv,2.50,over,0.86,0.91,0.33,0.32,0.24,0.20
6,2.84,145.35,2.71,3.19,0.77,NaN,NaN,melitz-model2,over,2004,melitz-model2-estimate-over-21126-sigma30.csv,3.00,over,0.89,0.93,0.38,0.37,0.24,0.09
7,2.93,38.21,2.75,3.24,0.31,NaN,NaN,melitz-model2,over,2011,melitz-model2-estimate-over-21126-sigma30.csv,3.00,over,0.90,0.98,0.36,0.34,0.22,0.25
8,2.92,44.65,2.72,3.18,0.49,NaN,NaN,melitz-model2,over,2017,melitz-model2-estimate-over-21126-sigma30.csv,3.00,over,0.85,0.91,0.35,0.32,0.20,0.20