### Combine Estimation Results

This notebook reads CSV files with date stamps (e.g., `-12726`) from the results folder and combines them into a single DataFrame.

In [8]:
import pandas as pd
import glob
import re
from pathlib import Path

In [9]:
# Get all CSV files in the results folder
results_folder = Path('../results')
all_csv_files = list(results_folder.glob('*.csv'))

# Filter to only include files with a date pattern (e.g., -12726)
# Pattern: filename containing a hyphen followed by digits before .csv
date_pattern = re.compile(r'-\d+(-[\w-]+)?\.csv$')
dated_files = [f for f in all_csv_files if date_pattern.search(f.name)]

print(f"Found {len(dated_files)} files with date stamps:")
for f in dated_files:
    print(f"  - {f.name}")

Found 10 files with date stamps:
  - bejk-estimate-exact-12726.csv
  - bejk-estimate-over-12726.csv
  - ek-estimate-exact-12726.csv
  - ek-estimate-over-12726.csv
  - krugman-estimate-exact-12726.csv
  - krugman-estimate-over-12726.csv
  - melitz-estimate-exact-12726.csv
  - melitz-estimate-exact-12926-sigma-theta.csv
  - melitz-estimate-over-12726.csv
  - melitz-estimate-over-12926-sigma-theta.csv

In [10]:
# Separate files into exact and over categories
exact_files = [f for f in dated_files if 'exact' in f.name]
over_files = [f for f in dated_files if 'over' in f.name]

print(f"Exact files ({len(exact_files)}):")
for f in exact_files:
    print(f"  - {f.name}")

print(f"\nOver files ({len(over_files)}):")
for f in over_files:
    print(f"  - {f.name}")

Exact files (5):
  - bejk-estimate-exact-12726.csv
  - ek-estimate-exact-12726.csv
  - krugman-estimate-exact-12726.csv
  - melitz-estimate-exact-12726.csv
  - melitz-estimate-exact-12926-sigma-theta.csv

Over files (5):
  - bejk-estimate-over-12726.csv
  - ek-estimate-over-12726.csv
  - krugman-estimate-over-12726.csv
  - melitz-estimate-over-12726.csv
  - melitz-estimate-over-12926-sigma-theta.csv

In [11]:
# Read and combine EXACT files
exact_dfs = []
for file in exact_files:
    df = pd.read_csv(file)
    df['source_file'] = file.name
    exact_dfs.append(df)

exact_df = pd.concat(exact_dfs, ignore_index=True)

# Read and combine OVER files
over_dfs = []
for file in over_files:
    df = pd.read_csv(file)
    df['source_file'] = file.name
    over_dfs.append(df)

over_df = pd.concat(over_dfs, ignore_index=True)

# Set display options to show 2 decimal places
pd.set_option('display.float_format', '{:.2f}'.format)

print(f"Exact DataFrame: {len(exact_df)} rows")
print(f"Over DataFrame: {len(over_df)} rows")

Exact DataFrame: 15 rows
Over DataFrame: 15 rows

In [12]:
# Display EXACT results
print("=== EXACT Estimation Results ===")
exact_df.sort_values(by = ["θ"], inplace=True)

exact_df

=== EXACT Estimation Results ===

,θ,J,p10,p90,Jpercentile,model_moment,data_moment,model,method,year,source_file
1,2.73,0.00,2.66,2.85,0.49,0.98,0.98,bejk,exact,2011,bejk-estimate-exact-12726.csv
0,2.82,0.00,2.73,2.93,0.14,0.93,0.93,bejk,exact,2004,bejk-estimate-exact-12726.csv
2,2.87,0.00,2.76,3.00,0.69,0.91,0.91,bejk,exact,2017,bejk-estimate-exact-12726.csv
10,3.30,0.00,3.10,3.83,0.02,0.98,0.98,melitz,exact,2011,melitz-estimate-exact-12726.csv
13,3.30,0.00,3.10,3.83,0.02,0.98,0.98,melitz,exact,2011,melitz-estimate-exact-12926-sigma-theta.csv
14,3.32,0.00,2.83,3.73,0.27,0.91,0.91,melitz,exact,2017,melitz-estimate-exact-12926-sigma-theta.csv
11,3.32,0.00,2.83,3.73,0.15,0.91,0.91,melitz,exact,2017,melitz-estimate-exact-12726.csv
9,3.50,0.00,3.06,3.90,0.19,0.93,0.93,melitz,exact,2004,melitz-estimate-exact-12726.csv
12,3.50,0.00,3.06,3.90,0.14,0.93,0.93,melitz,exact,2004,melitz-estimate-exact-12926-sigma-theta.csv
4,3.94,0.00,3.81,4.08,0.80,0.98,0.98,ek,exact,2011,ek-estimate-exact-12726.csv
3,4.09,0.00,3.92,4.23,0.98,0.93,0.93,ek,exact,2004,ek-estimate-exact-12726.csv
5,4.19,0.00,4.05,4.34,0.34,0.91,0.91,ek,exact,2017,ek-estimate-exact-12726.csv
7,4.90,0.00,4.73,5.12,0.66,0.98,0.98,krugman,exact,2011,krugman-estimate-exact-12726.csv
8,5.17,0.00,4.94,5.41,0.46,0.91,0.91,krugman,exact,2017,krugman-estimate-exact-12726.csv
6,5.19,0.00,4.96,5.57,0.48,0.93,0.93,krugman,exact,2004,krugman-estimate-exact-12726.csv

In [13]:
# Save the combined results to CSV
exact_df.to_csv('combined-exact-results.csv', index=False, float_format='%.2f')
over_df.to_csv('combined-over-results.csv', index=False, float_format='%.2f')
print("Saved: combined-exact-results.csv")
print("Saved: combined-over-results.csv")

Saved: combined-exact-results.csv
Saved: combined-over-results.csv

In [14]:
# Display OVER results
print("=== OVER Estimation Results ===")
over_df

=== OVER Estimation Results ===

,θ,J,p10,p90,Jpercentile,model_moment_1,data_moment_1,model_moment_2,data_moment_2,model_moment_3,data_moment_3,model,method,year,source_file
0,2.76,23.31,2.71,2.83,0.68,0.95,0.93,0.36,0.37,0.07,0.09,bejk,over,2004,bejk-estimate-over-12726.csv
1,2.80,173.18,2.74,2.88,1.00,0.96,0.98,0.34,0.34,0.07,0.25,bejk,over,2011,bejk-estimate-over-12726.csv
2,2.88,180.72,2.81,2.95,1.00,0.91,0.91,0.33,0.32,0.06,0.20,bejk,over,2017,bejk-estimate-over-12726.csv
3,4.00,10.74,3.91,4.12,0.38,0.95,0.93,0.36,0.37,0.09,0.09,ek,over,2004,ek-estimate-over-12726.csv
4,4.07,136.76,3.99,4.18,0.99,0.95,0.98,0.34,0.34,0.09,0.25,ek,over,2011,ek-estimate-over-12726.csv
5,4.18,139.25,4.09,4.31,1.00,0.91,0.91,0.32,0.32,0.07,0.20,ek,over,2017,ek-estimate-over-12726.csv
6,3.76,1390.47,3.56,3.92,1.00,1.28,0.93,0.25,0.37,0.23,0.09,krugman,over,2004,krugman-estimate-over-12726.csv
7,3.49,983.90,3.34,3.60,1.00,1.38,0.98,0.25,0.34,0.23,0.25,krugman,over,2011,krugman-estimate-over-12726.csv
8,3.82,1411.74,3.64,3.98,1.00,1.23,0.91,0.21,0.32,0.20,0.20,krugman,over,2017,krugman-estimate-over-12726.csv
9,3.59,133.16,3.38,3.91,0.86,0.90,0.93,0.34,0.37,0.21,0.09,melitz,over,2004,melitz-estimate-over-12726.csv
10,3.15,60.78,2.91,3.67,0.53,1.03,0.98,0.29,0.34,0.25,0.25,melitz,over,2011,melitz-estimate-over-12726.csv
11,3.08,287.52,2.60,3.82,0.92,0.98,0.91,0.23,0.32,0.25,0.20,melitz,over,2017,melitz-estimate-over-12726.csv
12,3.59,133.16,3.38,3.91,0.86,0.90,0.93,0.34,0.37,0.21,0.09,melitz,over,2004,melitz-estimate-over-12926-sigma-theta.csv
13,3.15,60.78,2.91,3.67,0.53,1.03,0.98,0.29,0.34,0.25,0.25,melitz,over,2011,melitz-estimate-over-12926-sigma-theta.csv
14,3.08,287.52,2.60,3.82,0.92,0.98,0.91,0.23,0.32,0.25,0.20,melitz,over,2017,melitz-estimate-over-12926-sigma-theta.csv